import { Inter } from "next/font/google";
import Header from "./components/Header";
import Footer from "./components/Footer";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className=" flex flex-col items-center  h-full  w-full">
          <Header></Header>
          <main className="w-full p-2">
            <div>{children}</div>
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
